// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	io "io"

	models "github.com/steffenrumpf/hdc/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockWriter is an autogenerated mock type for the Writer type
type MockWriter struct {
	mock.Mock
}

type MockWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWriter) EXPECT() *MockWriter_Expecter {
	return &MockWriter_Expecter{mock: &_m.Mock}
}

// Write provides a mock function with given fields: w, result
func (_m *MockWriter) Write(w io.Writer, result *models.Result) error {
	ret := _m.Called(w, result)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(io.Writer, *models.Result) error); ok {
		r0 = rf(w, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWriter_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockWriter_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - w io.Writer
//   - result *models.Result
func (_e *MockWriter_Expecter) Write(w interface{}, result interface{}) *MockWriter_Write_Call {
	return &MockWriter_Write_Call{Call: _e.mock.On("Write", w, result)}
}

func (_c *MockWriter_Write_Call) Run(run func(w io.Writer, result *models.Result)) *MockWriter_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Writer), args[1].(*models.Result))
	})
	return _c
}

func (_c *MockWriter_Write_Call) Return(_a0 error) *MockWriter_Write_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWriter_Write_Call) RunAndReturn(run func(io.Writer, *models.Result) error) *MockWriter_Write_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWriter creates a new instance of MockWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWriter {
	mock := &MockWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
