// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	repository "github.com/steffenrumpf/hdc/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// MockRepositoryClient is an autogenerated mock type for the RepositoryClient type
type MockRepositoryClient struct {
	mock.Mock
}

type MockRepositoryClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryClient) EXPECT() *MockRepositoryClient_Expecter {
	return &MockRepositoryClient_Expecter{mock: &_m.Mock}
}

// FetchIndex provides a mock function with given fields: repoURL
func (_m *MockRepositoryClient) FetchIndex(repoURL string) (*repository.Index, error) {
	ret := _m.Called(repoURL)

	if len(ret) == 0 {
		panic("no return value specified for FetchIndex")
	}

	var r0 *repository.Index
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*repository.Index, error)); ok {
		return rf(repoURL)
	}
	if rf, ok := ret.Get(0).(func(string) *repository.Index); ok {
		r0 = rf(repoURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Index)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(repoURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryClient_FetchIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchIndex'
type MockRepositoryClient_FetchIndex_Call struct {
	*mock.Call
}

// FetchIndex is a helper method to define mock.On call
//   - repoURL string
func (_e *MockRepositoryClient_Expecter) FetchIndex(repoURL interface{}) *MockRepositoryClient_FetchIndex_Call {
	return &MockRepositoryClient_FetchIndex_Call{Call: _e.mock.On("FetchIndex", repoURL)}
}

func (_c *MockRepositoryClient_FetchIndex_Call) Run(run func(repoURL string)) *MockRepositoryClient_FetchIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRepositoryClient_FetchIndex_Call) Return(_a0 *repository.Index, _a1 error) *MockRepositoryClient_FetchIndex_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryClient_FetchIndex_Call) RunAndReturn(run func(string) (*repository.Index, error)) *MockRepositoryClient_FetchIndex_Call {
	_c.Call.Return(run)
	return _c
}

// FetchOCITags provides a mock function with given fields: ociURL
func (_m *MockRepositoryClient) FetchOCITags(ociURL string) (*repository.Index, error) {
	ret := _m.Called(ociURL)

	if len(ret) == 0 {
		panic("no return value specified for FetchOCITags")
	}

	var r0 *repository.Index
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*repository.Index, error)); ok {
		return rf(ociURL)
	}
	if rf, ok := ret.Get(0).(func(string) *repository.Index); ok {
		r0 = rf(ociURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Index)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ociURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryClient_FetchOCITags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchOCITags'
type MockRepositoryClient_FetchOCITags_Call struct {
	*mock.Call
}

// FetchOCITags is a helper method to define mock.On call
//   - ociURL string
func (_e *MockRepositoryClient_Expecter) FetchOCITags(ociURL interface{}) *MockRepositoryClient_FetchOCITags_Call {
	return &MockRepositoryClient_FetchOCITags_Call{Call: _e.mock.On("FetchOCITags", ociURL)}
}

func (_c *MockRepositoryClient_FetchOCITags_Call) Run(run func(ociURL string)) *MockRepositoryClient_FetchOCITags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRepositoryClient_FetchOCITags_Call) Return(_a0 *repository.Index, _a1 error) *MockRepositoryClient_FetchOCITags_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryClient_FetchOCITags_Call) RunAndReturn(run func(string) (*repository.Index, error)) *MockRepositoryClient_FetchOCITags_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryClient creates a new instance of MockRepositoryClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryClient {
	mock := &MockRepositoryClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
