// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	models "github.com/steffenrumpf/hdc/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockChecker is an autogenerated mock type for the Checker type
type MockChecker struct {
	mock.Mock
}

type MockChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChecker) EXPECT() *MockChecker_Expecter {
	return &MockChecker_Expecter{mock: &_m.Mock}
}

// Check provides a mock function with given fields: hf
func (_m *MockChecker) Check(hf *models.Helmfile) (*models.Result, error) {
	ret := _m.Called(hf)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 *models.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.Helmfile) (*models.Result, error)); ok {
		return rf(hf)
	}
	if rf, ok := ret.Get(0).(func(*models.Helmfile) *models.Result); ok {
		r0 = rf(hf)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.Helmfile) error); ok {
		r1 = rf(hf)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChecker_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type MockChecker_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - hf *models.Helmfile
func (_e *MockChecker_Expecter) Check(hf interface{}) *MockChecker_Check_Call {
	return &MockChecker_Check_Call{Call: _e.mock.On("Check", hf)}
}

func (_c *MockChecker_Check_Call) Run(run func(hf *models.Helmfile)) *MockChecker_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Helmfile))
	})
	return _c
}

func (_c *MockChecker_Check_Call) Return(_a0 *models.Result, _a1 error) *MockChecker_Check_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChecker_Check_Call) RunAndReturn(run func(*models.Helmfile) (*models.Result, error)) *MockChecker_Check_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChecker creates a new instance of MockChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChecker {
	mock := &MockChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
