version: 2

project_name: hdc

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd
    binary: hdc
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

checksum:
  name_template: checksums.txt

changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: "^feat"
      order: 0
    - title: Bug Fixes
      regexp: "^fix"
      order: 1
    - title: Performance
      regexp: "^perf"
      order: 2
    - title: Other
      order: 999
  filters:
    exclude:
      - "^docs"
      - "^chore"
      - "^style"
      - "^ci"
