// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	repository "github.com/steffenrumpf/hdc/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// FetchIndex provides a mock function with given fields: repoURL
func (_m *MockClient) FetchIndex(repoURL string) (*repository.Index, error) {
	ret := _m.Called(repoURL)

	if len(ret) == 0 {
		panic("no return value specified for FetchIndex")
	}

	var r0 *repository.Index
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*repository.Index, error)); ok {
		return rf(repoURL)
	}
	if rf, ok := ret.Get(0).(func(string) *repository.Index); ok {
		r0 = rf(repoURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Index)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(repoURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_FetchIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchIndex'
type MockClient_FetchIndex_Call struct {
	*mock.Call
}

// FetchIndex is a helper method to define mock.On call
//   - repoURL string
func (_e *MockClient_Expecter) FetchIndex(repoURL interface{}) *MockClient_FetchIndex_Call {
	return &MockClient_FetchIndex_Call{Call: _e.mock.On("FetchIndex", repoURL)}
}

func (_c *MockClient_FetchIndex_Call) Run(run func(repoURL string)) *MockClient_FetchIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClient_FetchIndex_Call) Return(_a0 *repository.Index, _a1 error) *MockClient_FetchIndex_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_FetchIndex_Call) RunAndReturn(run func(string) (*repository.Index, error)) *MockClient_FetchIndex_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
