// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	os "os"

	mock "github.com/stretchr/testify/mock"
)

// MockFileReader is an autogenerated mock type for the FileReader type
type MockFileReader struct {
	mock.Mock
}

type MockFileReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileReader) EXPECT() *MockFileReader_Expecter {
	return &MockFileReader_Expecter{mock: &_m.Mock}
}

// Glob provides a mock function with given fields: pattern
func (_m *MockFileReader) Glob(pattern string) ([]string, error) {
	ret := _m.Called(pattern)

	if len(ret) == 0 {
		panic("no return value specified for Glob")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(pattern)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(pattern)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(pattern)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFileReader_Glob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Glob'
type MockFileReader_Glob_Call struct {
	*mock.Call
}

// Glob is a helper method to define mock.On call
//   - pattern string
func (_e *MockFileReader_Expecter) Glob(pattern interface{}) *MockFileReader_Glob_Call {
	return &MockFileReader_Glob_Call{Call: _e.mock.On("Glob", pattern)}
}

func (_c *MockFileReader_Glob_Call) Run(run func(pattern string)) *MockFileReader_Glob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockFileReader_Glob_Call) Return(_a0 []string, _a1 error) *MockFileReader_Glob_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFileReader_Glob_Call) RunAndReturn(run func(string) ([]string, error)) *MockFileReader_Glob_Call {
	_c.Call.Return(run)
	return _c
}

// ReadDir provides a mock function with given fields: path
func (_m *MockFileReader) ReadDir(path string) ([]os.DirEntry, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for ReadDir")
	}

	var r0 []os.DirEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]os.DirEntry, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) []os.DirEntry); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]os.DirEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFileReader_ReadDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadDir'
type MockFileReader_ReadDir_Call struct {
	*mock.Call
}

// ReadDir is a helper method to define mock.On call
//   - path string
func (_e *MockFileReader_Expecter) ReadDir(path interface{}) *MockFileReader_ReadDir_Call {
	return &MockFileReader_ReadDir_Call{Call: _e.mock.On("ReadDir", path)}
}

func (_c *MockFileReader_ReadDir_Call) Run(run func(path string)) *MockFileReader_ReadDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockFileReader_ReadDir_Call) Return(_a0 []os.DirEntry, _a1 error) *MockFileReader_ReadDir_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFileReader_ReadDir_Call) RunAndReturn(run func(string) ([]os.DirEntry, error)) *MockFileReader_ReadDir_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFile provides a mock function with given fields: path
func (_m *MockFileReader) ReadFile(path string) ([]byte, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for ReadFile")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFileReader_ReadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFile'
type MockFileReader_ReadFile_Call struct {
	*mock.Call
}

// ReadFile is a helper method to define mock.On call
//   - path string
func (_e *MockFileReader_Expecter) ReadFile(path interface{}) *MockFileReader_ReadFile_Call {
	return &MockFileReader_ReadFile_Call{Call: _e.mock.On("ReadFile", path)}
}

func (_c *MockFileReader_ReadFile_Call) Run(run func(path string)) *MockFileReader_ReadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockFileReader_ReadFile_Call) Return(_a0 []byte, _a1 error) *MockFileReader_ReadFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFileReader_ReadFile_Call) RunAndReturn(run func(string) ([]byte, error)) *MockFileReader_ReadFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFileReader creates a new instance of MockFileReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileReader {
	mock := &MockFileReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
